config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :cart
  
  root 'welcome#index'
  
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
	@user = User.find(params[:id])
  end

  def new
  end
  
  def create
    @user = User.new(user_params)
	
	@user.save
	redirect_to @user
  end
  
  private
	def user_params
		params.require(:user).permit(:email, :password, :name, :address, :phone_number)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cart/new.html.erb
<h1>Shopping Cart</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CS112Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user/new.html.erb
<h1>Hello, New User!</h1>

<p>Enter your details below to create a new account with us.</p>

<%= form_for :user do |f| %>

  <p><b>Account details</b></p>
  
  <p>
    <%= f.label :'E-mail address' %><br>
	<i><small>Note: This will be your username.</small></i><br>
	<%= f.text_field :email %>
  </p>
  
  <p>
    <%= f.label :Password %><br>
    <%= f.text_field :password %>
  </p>

  <br>
  <p><b>Personal details</b></p>
  
  <p>
    <%= f.label :Name %><br>
	<%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :'Shipping address' %><br>
	<%= f.text_area :address %>
  </p>
  
  <p>
    <%= f.label :'Phone number' %><br>
	<%= f.text_field :phone_number %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Hello, new User!</h1>

<p>Enter your details below to create a new account with us.</p>

<%= form_for :user, url: users_path do |f| %>

  <p><b>Account details</b></p>
  
  <p>
    <%= f.label :'E-mail address' %><br>
	<i><small>Note: This will be your username.</small></i><br>
	<%= f.text_field :email %>
  </p>
  
  <p>
    <%= f.label :Password %><br>
    <%= f.text_field :password %>
  </p>

  <br>
  <p><b>Personal details</b></p>
  
  <p>
    <%= f.label :Name %><br>
	<%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :'Shipping address' %><br>
	<%= f.text_area :address %>
  </p>
  
  <p>
    <%= f.label :'Phone number' %><br>
	<%= f.text_field :phone_number %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1>Summary of your details:</h1>

<p>
	<strong>Name:</strong>
	<%= @user.name %>
</p>

<p>
	<strong>E-mail address:</strong>
	<%= @user.email %>
</p>

<p>
	<strong>Address:</strong><br>
	<%= @user.address %>
</p>

<p>
	<strong>Phone number:</strong>
	<%= @user.phone_number %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome to the CS112 Shop!</h1>
<p>This is a simple shopping cart app for CS 112.</p>